server:
  port: 8086
spring:
  main:
    lazy-initialization: true
  aop:
    auto: true
  output:
    ansi:
      enabled: always
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 192.168.18.108:9200
  datasource:
    user-test:
      #driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/user_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
    # Hikari 连接池配置
    # 最小空闲连接数量
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 60000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 60000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    host: 127.0.0.1
    port: 6379
    database: 14
    password:

    sentinel:
      master: masterRedis
      nodes: 192.168.18.108:26379,192.168.18.108:26380,192.168.18.108:26381
      password: redistest
      database: 2
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 5
        # 最大空闲连接数 默认8
        max-idle: 10
        # 最小空闲连接数 默认0
        min-idle: 0
        # 链接等待时长 ms
        max-wait: 5000

  cache:
    jcache:
      config: classpath:/config/ehcache.xml
logging:
  level:
    root: info
  file:
    max-size: 10MB
    name: /logs/demo.log
